repos:
  # 1⃣ Format → Black
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.11

  # 2⃣ Lint + autofix → Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [--fix]     # auto-apply safe fixes
        language_version: python3.11
